# Generated by Django 3.1 on 2020-12-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advent',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=256, unique=True)),
                ('day', models.IntegerField()),
                ('advent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.advent')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('day', 'advent')},
            },
        ),
    ]
